_commit: f8ceb24
_src_path: https://github.com/orgpedia/template.mahdept.git
dept_name: Agriculture, Dairy Development, Animal Husbandry and Fisheries Department
dept_short_name: Agriculture
org_code: mahagri
